#!/usr/bin/env python3
"""dns-bench launcher: works from any cwd and when invoked through a symlink."""

import os
import sys

if sys.version_info < (3, 13):
    sys.exit("dns-bench needs Python 3.13 or newer (found %d.%d)" % sys.version_info[:2])

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from dnsbench.cli import main

if __name__ == "__main__":
    sys.exit(main())
